spring:
  profiles:
    active: dev

  datasource:
    url: "jdbc:postgresql://127.0.0.1:5432/condo_saas"
    username: "postgres"
    password: "postgres"
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    repair-on-migrate: true
    out-of-order: true
    ignore-migration-patterns: "*:missing"

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

app:
  jwt:
    issuer: condo
    secret: base64:YVD/WK/nr7LjsYsXjKqTfbEtaOTmwX6VE+obKhI0gVY=
    expirationMinutes: 120

logging:
  level:
    com.zaxxer.hikari: DEBUG
    org.springframework.jdbc.datasource: DEBUG
    org.flywaydb.core: DEBUG
    org.springframework.security: DEBUG